// Complete list of all documents in the case

export interface Document {
  id: string;
  name: string;
  category: "tax" | "contract" | "invoice" | "whatsapp" | "photo" | "official" | "technical" | "evidence";
  subcategory?: string;
  date?: string;
  source: string;
  path: string;
  description?: string;
  importance: "critical" | "high" | "medium" | "low";
  publicPath?: string; // Path in public folder for display
}

// Tax & Official Documents
export const taxDocuments: Document[] = [
  {
    id: "tax-001",
    name: "Уведомление налоговой DPG",
    category: "tax",
    date: "2025-12-31",
    source: "State Revenue Department Ekibastuz",
    path: "уведомление налоговой DPG.pdf",
    description: "Official tax notice claiming 129,829,500 KZT CIT",
    importance: "critical",
  },
  {
    id: "tax-002",
    name: "CIP Notice DPG - January 12",
    category: "tax",
    date: "2026-01-12",
    source: "Olzhas Sarsenov (DPG Director)",
    path: "2026.01.12 - CIP notice (DPG).pdf",
    description: "Internal notification of tax debt 131,030,500 KZT",
    importance: "critical",
  },
  {
    id: "tax-003",
    name: "DPG CIP - January 16",
    category: "tax",
    date: "2026-01-16",
    source: "Olzhas Sarsenov (DPG Director)",
    path: "2026.01.16 - DPG CIP.pdf",
    description: "Threat of asset seizure and service suspension",
    importance: "critical",
  },
];

// Official Registration Documents
export const officialDocuments: Document[] = [
  {
    id: "off-001",
    name: "Решение о перерегистрации DPG",
    category: "official",
    date: "2024-08-30",
    source: "DPG Registration",
    path: "РЕШЕНИЕ о перерегистрации_v.1.pdf",
    description: "Re-registration decision - Sarsenov as Director",
    importance: "critical",
  },
  {
    id: "off-002",
    name: "DPG Registration (Russian)",
    category: "official",
    date: "2024-08-30",
    source: "WhatsApp Dimitri",
    path: "WhatsApp_Dimitri_extracted/00002245-Digital Performance Group registration rus.pdf",
    description: "Official company registration document",
    importance: "high",
  },
  {
    id: "off-003",
    name: "VerCom License",
    category: "official",
    source: "WhatsApp Dimitri",
    path: "WhatsApp_Dimitri_extracted/00001942-лицензия VerCom.pdf",
    description: "Mining license for VerCom LLC (Enegix subsidiary)",
    importance: "high",
  },
];

// Contracts
export const contracts: Document[] = [
  {
    id: "con-001",
    name: "Contract of Sale and Delivery #7 - Hearst DMCC",
    category: "contract",
    date: "2024",
    source: "Hearst/DPG",
    path: "_ocr/00001374-CONTRACT_OF_SALE_AND_DELIVERY_7_HEARST_SOLUTIONS_DMCC.txt",
    description: "Equipment purchase contract - Hearst DMCC as Vendor, DPG as Buyer",
    importance: "critical",
  },
  {
    id: "con-002",
    name: "Hosting Agreement VerCom-DPG",
    category: "contract",
    source: "Enegix",
    path: "_ocr/docx/Hosting_Agreement_VerCom_DPG.txt",
    description: "Hosting services agreement between VerCom and DPG",
    importance: "critical",
  },
  {
    id: "con-003",
    name: "Contract DPG Hearst",
    category: "contract",
    source: "WhatsApp",
    path: "_ocr/docx/Contract_DPG_Hearst.txt",
    description: "Main contract between DPG and Hearst",
    importance: "critical",
  },
  {
    id: "con-004",
    name: "Contract Signed - Asset Purchase 5",
    category: "contract",
    source: "OCR Extract",
    path: "_ocr/contract_signed.txt",
    description: "Signed asset purchase agreement",
    importance: "high",
  },
  {
    id: "con-005",
    name: "Contract Pipe (Container pipes)",
    category: "contract",
    source: "Dimitri Enegix",
    path: "_ocr/contract_pipe.txt",
    description: "Agreement for container pipe purchase",
    importance: "medium",
  },
];

// Invoices
export const invoices: Document[] = [
  {
    id: "inv-001",
    name: "DPG Admin Invoice - $31,500",
    category: "invoice",
    date: "2024-11-05",
    source: "DPG to Hearst",
    path: "whatsapp_extract/yerbo_enegix/00002037-DPG admin invoice.pdf",
    description: "CRITICAL: Admin fee for Director + Accountant + Lawyer salaries",
    importance: "critical",
  },
  {
    id: "inv-002",
    name: "Invoice 204 - January prepayment",
    category: "invoice",
    date: "2024-01-24",
    source: "Dimitri Enegix",
    path: "WhatsApp_Dimitri_extracted/00001803-Invoice 204 - Jan 24, 2024 - prepayment for February.pdf",
    description: "Hosting prepayment invoice",
    importance: "medium",
  },
  {
    id: "inv-003",
    name: "Invoice 205 - February prepayment",
    category: "invoice",
    date: "2024-02-24",
    source: "Dimitri Enegix",
    path: "WhatsApp_Dimitri_extracted/00001949-Invoice 205 - Feb 24, 2024 - prepayment for March.pdf",
    description: "Hosting prepayment invoice",
    importance: "medium",
  },
  {
    id: "inv-004",
    name: "Invoice 206 - March prepayment",
    category: "invoice",
    date: "2024-03-25",
    source: "Dimitri Enegix",
    path: "WhatsApp_Dimitri_extracted/00001950-Invoice 206 - March 25, 2024 - prepayment for April.pdf",
    description: "Hosting prepayment invoice",
    importance: "medium",
  },
  {
    id: "inv-005",
    name: "Invoice 208 - May prepayment",
    category: "invoice",
    date: "2025-05-25",
    source: "Dimitri Enegix",
    path: "WhatsApp_Dimitri_extracted/00002116-Invoice 208 - May 25, 2025 - prepayment for June.pdf",
    description: "Hosting prepayment invoice",
    importance: "medium",
  },
  {
    id: "inv-006",
    name: "Invoice #2 DPG",
    category: "invoice",
    date: "2025-12-03",
    source: "Enegix Tech",
    path: "WhatsApp_Enegix_extracted/00002144-Invoice_№2_DPG.pdf",
    description: "DPG services invoice",
    importance: "medium",
  },
  {
    id: "inv-007",
    name: "Invoice #21 DPG",
    category: "invoice",
    date: "2025-02-28",
    source: "Enegix Tech",
    path: "WhatsApp_Enegix_extracted/00001146-Invoice_№21_DPG.pdf",
    description: "DPG services invoice",
    importance: "medium",
  },
  {
    id: "inv-008",
    name: "Statement of work DPG - December 2025",
    category: "invoice",
    date: "2025-12-03",
    source: "Enegix Tech",
    path: "WhatsApp_Enegix_extracted/00002143-Statement_of_work_performed_DPG_03.12.2025.pdf",
    description: "Work statement for DPG operations",
    importance: "high",
  },
  {
    id: "inv-009",
    name: "Statement of work DPG - February 2025",
    category: "invoice",
    date: "2025-02-28",
    source: "Enegix Tech",
    path: "WhatsApp_Enegix_extracted/00001138-Statement_of_work_performed_DPG_28.02.2025.pdf",
    description: "Work statement for DPG operations",
    importance: "high",
  },
];

// Technical Documents
export const technicalDocuments: Document[] = [
  {
    id: "tech-001",
    name: "Enegix Commercial Offer - Off-grid 40MW",
    category: "technical",
    date: "2023-12-19",
    source: "Enegix",
    path: "00015514-20231219 Enegix Commercial Offer - off-grid 40MW KZ.pdf",
    description: "Original commercial offer from Enegix",
    importance: "high",
  },
  {
    id: "tech-002",
    name: "Price list of works and services 2025",
    category: "technical",
    date: "2025",
    source: "Enegix Tech",
    path: "WhatsApp_Enegix_extracted/00001193-Price_list_of_works_and_services_by_miner_models_for_2025.pdf",
    description: "Service pricing for miner models",
    importance: "medium",
  },
  {
    id: "tech-003",
    name: "Quotation - DPG Almaty",
    category: "technical",
    source: "DPG",
    path: "DPG_Digital_Performance_Group/00019232-QT for Digital Performance Group(MM Dubai UAE - Almaty).pdf",
    description: "Quotation for DPG Almaty operations",
    importance: "medium",
  },
  {
    id: "tech-004",
    name: "Quotation - DPG Ekibastuz",
    category: "technical",
    source: "DPG",
    path: "DPG_Digital_Performance_Group/00024153-QT for Digital Performance Group(MM Dubai UAE - Ekibastuz) (1).pdf",
    description: "Quotation for DPG Ekibastuz operations",
    importance: "medium",
  },
];

// Photos - Site and Equipment
export const photos: Document[] = [
  {
    id: "photo-001",
    name: "Enegix Site Photo 1",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix1.jpg",
    description: "Mining facility exterior",
    importance: "medium",
    publicPath: "/evidence/photos/enegix1.jpg",
  },
  {
    id: "photo-002",
    name: "Enegix Site Photo 2",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix2.jpg",
    description: "Mining equipment",
    importance: "medium",
    publicPath: "/evidence/photos/enegix2.jpg",
  },
  {
    id: "photo-003",
    name: "Enegix Site Photo 3",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix3.jpg",
    description: "Container facility",
    importance: "medium",
    publicPath: "/evidence/photos/enegix3.jpg",
  },
  {
    id: "photo-004",
    name: "Enegix Site Photo 4",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix4.jpg",
    description: "Mining hardware",
    importance: "medium",
    publicPath: "/evidence/photos/enegix4.jpg",
  },
  {
    id: "photo-005",
    name: "Enegix Site Photo 5",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix5.jpg",
    description: "Facility operations",
    importance: "medium",
    publicPath: "/evidence/photos/enegix5.jpg",
  },
  {
    id: "photo-006",
    name: "Enegix Site Photo 6",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix6.jpg",
    description: "Container setup",
    importance: "medium",
    publicPath: "/evidence/photos/enegix6.jpg",
  },
  {
    id: "photo-007",
    name: "Enegix Site Photo 7",
    category: "photo",
    source: "Photos folder",
    path: "Photos/enegix7.jpg",
    description: "Site infrastructure",
    importance: "medium",
    publicPath: "/evidence/photos/enegix7.jpg",
  },
  {
    id: "photo-008",
    name: "Photo June 2024",
    category: "photo",
    date: "2024-06-13",
    source: "Root folder",
    path: "PHOTO-2024-06-13-15-07-11.jpg",
    description: "Site documentation",
    importance: "medium",
    publicPath: "/evidence/photos/PHOTO-2024-06-13-15-07-11.jpg",
  },
  {
    id: "photo-009",
    name: "Photo July 2024",
    category: "photo",
    date: "2024-07-04",
    source: "Root folder",
    path: "PHOTO-2024-07-04-09-03-26.jpg",
    description: "Site documentation",
    importance: "medium",
    publicPath: "/evidence/photos/PHOTO-2024-07-04-09-03-26.jpg",
  },
  {
    id: "photo-010",
    name: "Photo August 2024 (1)",
    category: "photo",
    date: "2024-08-13",
    source: "Root folder",
    path: "PHOTO-2024-08-13-18-18-26.jpg",
    description: "Site documentation",
    importance: "medium",
    publicPath: "/evidence/photos/PHOTO-2024-08-13-18-18-26.jpg",
  },
  {
    id: "photo-011",
    name: "Photo August 2024 (2)",
    category: "photo",
    date: "2024-08-30",
    source: "Root folder",
    path: "PHOTO-2024-08-30-13-39-59.jpg",
    description: "Site documentation",
    importance: "medium",
    publicPath: "/evidence/photos/PHOTO-2024-08-30-13-39-59.jpg",
  },
  {
    id: "photo-012",
    name: "Photo April 2025",
    category: "photo",
    date: "2025-04-24",
    source: "Root folder",
    path: "PHOTO-2025-04-24-16-49-26.jpg",
    description: "Site documentation",
    importance: "medium",
    publicPath: "/evidence/photos/PHOTO-2025-04-24-16-49-26.jpg",
  },
];

// WhatsApp Evidence - Key Messages
export const whatsappEvidence: Document[] = [
  {
    id: "wa-001",
    name: "DPG Company Transfer Chat",
    category: "whatsapp",
    subcategory: "DPG Transfer",
    source: "WhatsApp - DPG company transfer",
    path: "WhatsApp_DPG_extracted/",
    description: "Critical chat proving Enegix created and controlled DPG",
    importance: "critical",
  },
  {
    id: "wa-002",
    name: "Yerbo Enegix Chat",
    category: "whatsapp",
    subcategory: "Yerbo",
    source: "WhatsApp - Yerbo Enegix",
    path: "WhatsApp_Yerbo_extracted/",
    description: "Communications with Enegix CEO",
    importance: "critical",
  },
  {
    id: "wa-003",
    name: "Dimitri Enegix Chat",
    category: "whatsapp",
    subcategory: "Dimitri",
    source: "WhatsApp - Dimitri Enegix",
    path: "WhatsApp_Dimitri_extracted/",
    description: "Communications with Enegix Sales Director",
    importance: "critical",
  },
  {
    id: "wa-004",
    name: "Hearts x Enegix Tech Chat",
    category: "whatsapp",
    subcategory: "Tech Team",
    source: "WhatsApp - Hearts × Enegix Tech team",
    path: "WhatsApp_Enegix_extracted/",
    description: "Technical operations communications",
    importance: "high",
  },
];

// All documents combined
export const allDocuments: Document[] = [
  ...taxDocuments,
  ...officialDocuments,
  ...contracts,
  ...invoices,
  ...technicalDocuments,
  ...photos,
  ...whatsappEvidence,
];

// Statistics
export const documentStats = {
  total: allDocuments.length,
  byCategory: {
    tax: taxDocuments.length,
    official: officialDocuments.length,
    contract: contracts.length,
    invoice: invoices.length,
    technical: technicalDocuments.length,
    photo: photos.length,
    whatsapp: whatsappEvidence.length,
  },
  byImportance: {
    critical: allDocuments.filter(d => d.importance === "critical").length,
    high: allDocuments.filter(d => d.importance === "high").length,
    medium: allDocuments.filter(d => d.importance === "medium").length,
    low: allDocuments.filter(d => d.importance === "low").length,
  },
};
